-- 로그인(test_member1, pw1234)
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NAME, GENDER, 
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE  
FROM TB_MEMBER
WHERE MEMBER_ID = 'test_member1'
AND MEMBER_PW = 'pw1234';