-- 테이블 생성
CREATE TABLE SMILEGATE (
	MEMBER_NO NUMBER PRIMARY KEY,
	LOGIN_ID VARCHAR2(50) NOT NULL,
	LOGIN_PW VARCHAR2(50) NOT NULL,
	GAME_NICKNAME VARCHAR(50) UNIQUE
	);
COMMENT ON COLUMN SMILEGATE.MEMBER_NO 		IS '회원번호';
COMMENT ON COLUMN SMILEGATE.LOGIN_ID 		IS '아이디';
COMMENT ON COLUMN SMILEGATE.LOGIN_PW 		IS '비밀번호';
COMMENT ON COLUMN SMILEGATE.GAME_NICKNAME 	IS '닉네임';
	
CREATE TABLE INFORMATION (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(50),
	EMP_NO CHAR(14),
	PHONE CHAR(11),
	MEMBER_ADDRESS VARCHAR2(100),
	MEMBER_DEL_FL CHAR(1) DEFAULT 'N',
	FOREIGN KEY (MEMBER_NO) REFERENCES SMILEGATE(MEMBER_NO)
	);
COMMENT ON COLUMN INFORMATION.MEMBER_NO 		IS '회원번호';
COMMENT ON COLUMN INFORMATION.MEMBER_NAME 		IS '회원이름';
COMMENT ON COLUMN INFORMATION.EMP_NO 			IS '주민등록번호';
COMMENT ON COLUMN INFORMATION.PHONE 			IS '휴대폰번호';
COMMENT ON COLUMN INFORMATION.MEMBER_ADDRESS 	IS '주소';
COMMENT ON COLUMN INFORMATION.MEMBER_DEL_FL 	IS '탈퇴여부';

CREATE TABLE LOSTARK (
	GAME_NICKNAME VARCHAR2(50) UNIQUE,
	GAME_EXPERIENCE NUMBER,
	GAME_LEVEL NUMBER,
	ITEM_NO NUMBER PRIMARY KEY,
	MAP_NO NUMBER UNIQUE,
	FOREIGN KEY (GAME_NICKNAME) REFERENCES SMILEGATE(GAME_NICKNAME)
	);
COMMENT ON COLUMN LOSTARK.GAME_NICKNAME 	IS '닉네임';
COMMENT ON COLUMN LOSTARK.GAME_EXPERIENCE 	IS '경험치';
COMMENT ON COLUMN LOSTARK.GAME_LEVEL 		IS '레벨';
COMMENT ON COLUMN LOSTARK.ITEM_NO 			IS '아이템번호';
COMMENT ON COLUMN LOSTARK.MAP_NO 			IS '지도번호';

CREATE TABLE ITEMLIST (
	ITEM_NO NUMBER PRIMARY KEY,
	ITEM_NAME VARCHAR2(50),
	ITEM_POWER NUMBER,
	ITEM_LEVEL NUMBER,
	ITEM_RARE VARCHAR2(15),
	FOREIGN KEY (ITEM_NO) REFERENCES LOSTARK(ITEM_NO)
	);
COMMENT ON COLUMN ITEMLIST.ITEM_NO 		IS '아이템번호';
COMMENT ON COLUMN ITEMLIST.ITEM_NAME 	IS '아이템이름';
COMMENT ON COLUMN ITEMLIST.ITEM_POWER 	IS '아이템공격력';
COMMENT ON COLUMN ITEMLIST.ITEM_LEVEL 	IS '아이템착용가능레벨';
COMMENT ON COLUMN ITEMLIST.ITEM_RARE 	IS '아이템희귀도';

CREATE TABLE GAMEMAP (
	MAP_NO NUMBER PRIMARY KEY,
	MAP_NAME VARCHAR2(30),
	MAP_DANGER NUMBER,
	MAP_MIN_LEVEL NUMBER,
	FOREIGN KEY (MAP_NO) REFERENCES LOSTARK(MAP_NO)
	);
COMMENT ON COLUMN GAMEMAP.MAP_NO 			IS '지도번호';
COMMENT ON COLUMN GAMEMAP.MAP_NAME 			IS '지도이름';
COMMENT ON COLUMN GAMEMAP.MAP_DANGER 		IS '지역위험도';
COMMENT ON COLUMN GAMEMAP.MAP_MIN_LEVEL 	IS '지역입장레벨';






SELECT * FROM SMILEGATE;
SELECT * FROM INFORMATION;
SELECT * FROM LOSTARK;
SELECT * FROM ITEMLIST;
SELECT * FROM GAMEMAP;

