-- 01. example 계정을 생성하고 개채생성, 변경, 제거권한과,
--     DB연결 권한을 추가하고example2 계정을 생성하고 DB연결 권한과 VIEW 생성 권한을 추가한다.
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER example IDENTIFIED BY "123456";
GRANT CREATE SESSION TO example;
GRANT CREATE TABLE TO example;
GRANT CONNECT, RESOURCE, CREATE VIEW TO example;
ALTER USER example DEFAULT TABLESPACE "A230724"
QUOTA 10M ON "A230724";

CREATE USER example2 IDENTIFIED BY "1234567";
GRANT CREATE SESSION, CREATE VIEW TO example2;
ALTER USER example2 DEFAULT TABLESPACE "A230724"
QUOTA 10M ON "A230724";

-- 02. example2 계정의 DB연결 권한을 회수 후 계정 삭제한다.
REVOKE CREATE VIEW FROM example_ysk2;
DROP USER example2 CASCADE;

-- 03. example계정으로 접속해서 테이블 정의서를 참고하여 MEMBER 테이블과 BOARD 테이블을 생성한다.

-- MEMBER 테이블
CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2 (30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2 (30) NOT NULL,
	PHONE_NUMBER VARCHAR2 (20),
	DELETE_YN CHAR DEFAULT 'N',
	CHECK (DELETE_YN IN('Y', 'N'))
	);
	
COMMENT ON COLUMN MEMBER.MEMBER_NO 			IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID			IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD 	IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER 		IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN		 	IS '삭제여부';


-- BOARD 테이블(BOARD_WRITER 컬럼은 MEMBER테이블의 MEMBER_NO컬럼에 대한 외래키 제약조건설정)
CREATE TABLE BOARD (
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2 (300) NOT NULL,
	BOARD_CONTENT VARCHAR2 (4000) NOT NULL,
	BOARD_WRITER NUMBER REFERENCES MEMBER(MEMBER_NO),
	CREATE_DATE DATE DEFAULT SYSDATE
	);

COMMENT ON COLUMN BOARD.BOARD_NO 		IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE		IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT 	IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER	IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE	 	IS '작성일자';


-- 04. MEMBER 테이블과 BOARD 테이블에 다음과 같은 데이터를 추가한다.
-- 단, 회원번호와 글번호는 시퀀스를 생성하여 추가한다.
-- 시퀀스 :
-- SEQ_MEMBER_NO : 100부터 시작하여 100씩 증가
-- SEQ_BOARD_NO : 1부터 시작하여 1씩 증가

CREATE SEQUENCE SEQ_NO
   START WITH 100 -- 처음 발생시킬 시작값 지정, 생략하면 자동 1이 기본
   INCREMENT BY 100 -- 다음 값에 대한 증가치, 생략하면 자동 1이 기본
;

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD)
VALUES(SEQ_NO.NEXTVAL, 'step1', 'step11');
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES(SEQ_NO.NEXTVAL, 'step2', 'step22', '010-1111-2222');
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD)
VALUES(SEQ_NO.NEXTVAL, 'step3', 'step33');

COMMIT;

SELECT * FROM MEMBER;

CREATE SEQUENCE SEQ_NO1
   START WITH 1 -- 처음 발생시킬 시작값 지정, 생략하면 자동 1이 기본
   INCREMENT BY 1 -- 다음 값에 대한 증가치, 생략하면 자동 1이 기본
;


INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, CREATE_DATE)
VALUES(SEQ_NO1.NEXTVAL, '첫 글', '스텝평가', '100', '2023-03-12');
INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, CREATE_DATE)
VALUES(SEQ_NO1.NEXTVAL, '두 번째 글', '재밌다', '300', '2023-03-12');
INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, CREATE_DATE)
VALUES(SEQ_NO1.NEXTVAL, '세 번째 글', '하하하', '200', '2023-03-12');

COMMIT;

SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, MEMBER_ID 작성자, TO_CHAR(CREATE_DATE,'YY/MM/DD') 작성일
FROM BOARD
JOIN MEMBER ON (MEMBER_NO = BOARD_WRITER)
ORDER BY 글번호 DESC;



