-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호

-- MEMBER 테이블에 INSERT하기
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
	  'dbs1128218@naver.com', 
	  '123123', 
	  'dbs6312', 
	  '01056764826', 
	  '서울시', 
	  DEFAULT, DEFAULT)
;

COMMIT;

-- 이메일, 비밀번호가 일치하는 회원의
-- 닉네임, 전화번호, 주소 수정
UPDATE MEMBER
SET MEMBER_NICKNAME = '변경된 닉네임',
	MEMBER_TEL = '00002222113',
	MEMBER_ADDRESS = '부산'
WHERE MEMBER_EMAIL = 'dbs1128218@naver.com'
AND MEMBER_PW = '123123'
;



UPDATE MEMBER
SET MEMBER_PW = '변경된 비밀번호'
WHERE MEMBER_EMAIL = '이메일'
AND MEMBER_PW = '비밀번호';


SELECT MEMBER_NO , MEMBER_NICKNAME , MEMBER_TEL , MEMBER_ADDRESS , 
	TO_CHAR (ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_EMAIL = 'aasd'
AND MEMBER_PW = '1234'
AND MEMBER_DEL_FL = 'N';


SELECT * FROM MEMBER
ORDER BY MEMBER_NO ASC;

UPDATE MEMBER
SET MEMBER_NICKNAME = '별명',
MEMBER_TEL = '01022050123'
WHERE MEMBER_NO = 3 ;

SELECT *
FROM MEMBER ;


UPDATE MEMBER
SET MEMBER_DEL_FL = 'N'
WHERE MEMBER_NO = '3'
AND MEMBER_PW = 'asd' ;

COMMIT;


-- BOARD 테이블에 INSERT 하기
-- (실행 후 COMMIT / ROLLBACK 무조건 수행)

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '자나', '정말?', DEFAULT, DEFAULT, DEFAULT, 4 );

COMMIT;



-- 게시글 목록 조회(작성자 닉네임 포함)
-- 1) 삭제되지 않은 글
-- 2) 최신글 순(BOARD_NO 내림차순)
SELECT BOARD_NO, BOARD_TITLE, 
	TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT, MEMBER_NO, MEMBER_NICKNAME 
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT *
FROM BOARD;

